### ISSUE TITLE
[PR] Change icon does not work

### ISSUE THREAD

**Issue by ChipCE** [AdrianTM/mx-menu-editor#1]
Hi, I found a problem in MX menu editor 19.9 

### Expected Behavior
Can change application icon

### Current Behavior
The icon review showed but nothing change when "Save Changes" button clicked.

### Steps to Reproduce
1. Open MX menu editor
2. Select an application
3. Change icon with a png image (tested with difference sizes)
4. Make sure the icon appear in the review section
5. Click "Save changes" button

The icon config in <doce>Advanced editor</code> does not updated when I clicked the "Save changes" button.

### System information
<code>
Linux 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux
MX menu editor 19.9
</code>

**Comment by AdrianTM** [comment]
Can't replicate that, I am able to change and save the icon.

What the mx-menu-editor does when you change an application is save a new .desktop file to ~/.local/share/applications/ see if you can find the specific .desktop file there and if inside the icon path look OK... not sure what is going on in your case.

**Comment by ChipCE** [comment]
I can replicate on my other machine running newest version of MX linux. Maybe the steps I use to replicate it are difference?
This is the step

1. Open MX menu editor and select <code>Add custom application</code>
2. Enter name,comment,command,category but NOT set the icon
3. Click <code>Save changes</code>
4. Close and re open MX menu editor
5. Select the above custom application of the left menu 
6. Change icon 
7. Click <code>Save changes</code>
This is the before and after i change the icon
<pre>
[Desktop Entry]
Name=FreeCad
Exec=/home/chip/Data/Application/FreeCAD_0.18-16146-rev1-Linux-Conda_Py3Qt5_glibc2.12-x86_64.AppImage
Comment=freecad appimage
Terminal=false
Type=Application
Categories=Graphics;
</pre>

<pre>
[Desktop Entry]
Name=FreeCad
Exec=/home/chip/Data/Application/FreeCAD_0.18-16146-rev1-Linux-Conda_Py3Qt5_glibc2.12-x86_64.AppImage
Comment=freecad appimage
Terminal=false
Type=Application
Categories=Graphics;
</pre>

**Comment by AdrianTM** [comment]
Thanks for the clarification, I tried editing an existing app not adding a custom one, probably that made the difference I will take a look.

**Comment by AdrianTM** [comment]
Should be fixed now, I made some other small improvements, package in /debs also coming shortly in the repo.
